---
version: '3'

networks:
  fauna:

services:
  console:
    container_name: fauna-console
    tty: true
    stdin_open: true
    build:
      context: .
    depends_on:
      - ldap
    volumes:
      - .:/src
    environment:
      - LDAPURI=ldap://fauna-ldap:1389
      - WAIT=20
    networks:
      - fauna


  # https://hub.docker.com/r/openidentityplatform/opendj/
  ldap:
    container_name: fauna-ldap
    image: openidentityplatform/opendj:latest
    ports:
      - 389:1389
      - 636:1636
    environment:
      BASE_DN: dc=earth
      ROOT_USER_DN: cn=Darwin
      ROOT_PASSWORD: naturalSelection
    networks:
      - fauna
