---
version: '3'

networks:
  fauna:

services:

  ldap:
    container_name: fauna
    build:
      context: ./server
      args:
        version: 4.4.4
    ports:
      - 389:389
      - 636:636
      - 4444:4444
    healthcheck:
      test: curl ldap://127.0.0.1:389/dc=earth || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 1
    environment:
      BASE_DN: dc=earth
      ROOT_USER_DN: cn=Darwin
      ROOT_PASSWORD: naturalSelection
    networks:
      - fauna
